on:
  push:
    branches: [ "dev" ]
jobs:
  #TODO: AJUSTAR PARA IOS
  #ios-build:
    #name: iOS Dev Build
    #runs-on: self-hosted
    #steps:
      #- name: Show self-hosted machine infomation
      #  run: uname -a
      #- name: Cancel previous runss
      #  uses: styfle/cancel-workflow-action@0.9.1
      #- name: Checkout repo from dev branch
      #  uses: actions/checkout@v3
      #  with:
      #    ref: dev
      #- name: Install npm dependency
      #  run: yarn install
      #- name: Cache cocoapods
      #  uses: actions/cache@v3
      #  with:
      #    path: /ios/Pods
      #    key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pods-
      #- name: Install pod dependency
      #  run: |
      #    cd ios
      #    bundle exec pod install
      #- name: Build iOS JS Bundle
      #  run: |
      #    yarn run package-ios
      #- name: Install bundler
      #  run: |
      #    cd ios
      #    gem install bundler
      #- name: Install gem plugins
      #  run: |
      #    cd ios
      #    bundle install
      #- name: Run fastlane
      #  run: |
      #    cd ios
      #    bundle exec fastlane build_testflight
  android-build:
    name: Android Dev Build
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0
      - name: Checkout repo from dev branch
        uses: actions/checkout@v4.0.0
        with:
          ref: dev
      - name: Install npm dependency
        run: yarn install

      - name: Replace fonts.gradle
        run: |
          cp /home/runner/work/apptailwind/apptailwind/fonts.gradle /home/runner/work/apptailwind/apptailwind/node_modules/react-native-vector-icons/fonts.gradle
      - name: install java 17
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install openjdk-17-jdk openjdk-17-jre

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.1.0
        with:
          cmdline-tools-version: 9.0
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
      - uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0
      - name: Execute Gradle build
        run: |
          cd /home/runner/work/apptailwind/apptailwind/android
          sudo apt-get install dos2unix
          dos2unix gradlew
          ./gradlew build
      - name: Build Android JS Bundle
        run: |
          cd /home/runner/work/apptailwind/apptailwind/android
          ./gradlew bundleRelease
      - name: Install Ruby
        run: |
          cd /home/runner/work/apptailwind/apptailwind/android
          sudo apt update
          sudo apt install ruby-full
      - name: Install bundler
        run: |
          cd /home/runner/work/apptailwind/apptailwind/android
          sudo gem install bundler
      - name: Install gem plugins
        run: |
          cd /home/runner/work/apptailwind/apptailwind/android
          sudo bundle install
      - name: Run fastlane
        run: |
          cd /home/runner/work/apptailwind/apptailwind/android
          sudo fastlane add_plugin appcenter
          sudo fastlane add_plugin versioning
          sudo bundle exec fastlane build
